### ISSUE TITLE
0.12.0 is out - lets break some ****

### ISSUE THREAD

**Issue by ofTheo** [openframeworks/apothecary#279]
🙂

- [ ] Going to remove boost and poco from apothecary. 
- [ ] Upgrade runners ( macOS 10.15 is not working any more ) 
- [ ] Merge @danoli3's changes for android etc 

@danoli3 there are some aarch64 changes I got working just fyi 
https://github.com/openframeworks/apothecary/commit/8c57dcf4203d855bd4174df74bccd97b04c30d79 
https://github.com/openframeworks/apothecary/commit/fea8f77186429c46988ac73c7c93c0c6624ee4c3

Reminder we are only doing 64bit going forward so no VS 32bit libs etc.

**Comment by ofTheo** [comment]
Looking into addons there are quite a lot that still use Poco. 

Wondering if we should maybe move ofxPoco to openFrameworks/ofxPoco with all the libs in place and then people can download as needed for 0.13.0 onwards?

cc @bakercp @danzeeeman

**Comment by bakercp** [comment]
Most of my add-ons use it. So if it's available somewhere that would be great.

**Comment by danzeeeman** [comment]
+1 for getting ofxPoco out of the core!  There were times where I needed
more of what poco offers than what ofxPoco has in it.  Having to swap out
the core was a bit frustrating cause it made shipping the addon for others
to use challenging.

Dan

**Comment by danoli3** [comment]
Okay I'll merge into latest master apothecary/android pr now and start this underway now

Noticing the sizes of VS libs is now very much more compressed to, I think most are just release now but down from like 700mb to 30-50mb 

That's like 2.2gb deployed to 400-500 with arm64, x86_64 (64bit) 

Once we get it mergable we can do a release called daily instead of nightly tag and use to download and test on PR / scripts on openFrameworks core to start testing and merging with updated libraries

**Comment by ofTheo** [comment]
@danoli3 - curious why the **bleeding** branch isn't uploading the files anymore. was that intentional? 
is macOS safe to enable in terms of GitHub actions?

is it possible to get a short list of the platforms that need the most work in **bleeding**?

**Comment by danoli3** [comment]
Not completely sure, might need to trigger a rebuild with a new commit on
that branch! Let me do that now.

macOS is pretty much ready to go I think I was battling Cairo last one to
do.

I’m doing super better I think I can commit to this week sorting everything
out

**Comment by danoli3** [comment]
Okay I think we broken a lot of things, but overall I think fixed most of the big issues.
Been a bit slow getting it all in but this has been a great test of my abilities post these hectic infections and health problems so glad to have purpose and all that

### Done
- Dependancies all updated to latest 
- VS2022 MSVC - ARM64/ARM64EC/64
- iOS/macOS/tvOS 
- C17 - C++23 default 
- xCFramework system 
- GitHub Artifacts used for cache / optimisation of builds if no version changes 
- Android NDK 23 libs (arm64,armv7, x86, x86_64) C++17
- CMake Build Systems mostly generated for all dependancies (at upstream mostly) 

## Experimental
- Emscripten working with latest stuff / tested (pthead/memory64) 
- catOS/visionOS/tvOS - all building and linking - need the ofxMetal PR) to build via MetalANGLE as metal target required


## TODO:
- Android PR updated in core linked to latest binaries
- Android Libraries updated to NDK 25 latest (faster) / C++- drops x86 though
- Linux 64 - gcc14 might as well update the cmake scripts here and test 
- Linux arch7  -gcc14 - same - test with fastest compile options 
- Linux arm64 -gcc14 - same - test with fastest compile options 
- pkgconfig files / cmake config install files alongside some binaries to help core CmakeList push 

## Todo: Experimental:
- Clang VS2022 lib release - mostly working just some depends some issues

**Comment by NickHardeman** [comment]
@danoli3 this is great, thank you for all of the updates and effort.
